# Prometheus - Project Parallel
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'service-health'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://servicio-autenticacion:8001/salud
          - http://servicio-historias:8002/salud
          - http://servicio-audio:8003/salud
          - http://servicio-ia:8004/salud
          - http://nginx:80/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __param_module
        replacement: http_2xx
      - source_labels: [__param_target]
        target_label: __param_target

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
